-- Sincronizar fotos de miembros con archivos actuales
-- Ejecutar en Supabase → SQL Editor → Run

begin;
update public.miembros set foto = 'Benjamín Alexander Vásquez Zolorsa.png' where nombre = 'Benjamín Alexander Vásquez Zolorsa' and (foto is distinct from 'Benjamín Alexander Vásquez Zolorsa.png');
update public.miembros set foto = 'Wladimir Antonio Sepúlveda Fuentes.png' where nombre = 'Wladimir Antonio Sepúlveda Fuentes' and (foto is distinct from 'Wladimir Antonio Sepúlveda Fuentes.png');
update public.miembros set foto = 'Matias Ignacio Vega Abarca.png' where nombre = 'Matias Ignacio Vega Abarca' and (foto is distinct from 'Matias Ignacio Vega Abarca.png');
update public.miembros set foto = 'Martina Francisca Escalante Cornejo.png' where nombre = 'Martina Francisca Escalante Cornejo' and (foto is distinct from 'Martina Francisca Escalante Cornejo.png');
update public.miembros set foto = 'Rosales Sánchez, Héctor Manuel.png' where nombre = 'Héctor Manuel Rosales Sanchez' and (foto is distinct from 'Rosales Sánchez, Héctor Manuel.png');
update public.miembros set foto = 'Mario Alejandro Rossel Poblete.png' where nombre = 'Mario Alejandro Rossel Poblete' and (foto is distinct from 'Mario Alejandro Rossel Poblete.png');
update public.miembros set foto = 'Graciela Del Carmen Arpe Torres.jpeg' where nombre = 'Graciela Del Carmen Arpe Torres' and (foto is distinct from 'Graciela Del Carmen Arpe Torres.jpeg');
update public.miembros set foto = 'Isabella Esperanza Illanes Arpe.png' where nombre = 'Isabella Esperanza Illanes Arpe' and (foto is distinct from 'Isabella Esperanza Illanes Arpe.png');
update public.miembros set foto = 'José Manuel Illanes Ceballos.png' where nombre = 'José Manuel Illanes Ceballos' and (foto is distinct from 'José Manuel Illanes Ceballos.png');
update public.miembros set foto = 'Roberto Pablo Illanes Postigo.png' where nombre = 'Roberto Pablo Illanes Postigo' and (foto is distinct from 'Roberto Pablo Illanes Postigo.png');
update public.miembros set foto = 'Matías Alejandro Fuentes Martinez.png' where nombre = 'Matías Alejandro Fuentes Martinez' and (foto is distinct from 'Matías Alejandro Fuentes Martinez.png');
update public.miembros set foto = 'Matías Valentín Leyes Campos.png' where nombre = 'Matias Valentin Leyes Campos' and (foto is distinct from 'Matías Valentín Leyes Campos.png');
update public.miembros set foto = 'Nahuel Nicolás Leyes Campos.png' where nombre = 'Nahuel Nicolás Leyes Campos' and (foto is distinct from 'Nahuel Nicolás Leyes Campos.png');
update public.miembros set foto = 'Edgardo José Abarca Neira.png' where nombre = 'Edgardo Jose Abarca Neira' and (foto is distinct from 'Edgardo José Abarca Neira.png');
update public.miembros set foto = 'Omar Ramon Ayala Roman.png' where nombre = 'Omar Ramon Ayala Roman' and (foto is distinct from 'Omar Ramon Ayala Roman.png');
update public.miembros set foto = 'Eduardo David Enrique Naranjo Gutiérrez.png' where nombre = 'Eduardo David Enrique Naranjo Gutierrez' and (foto is distinct from 'Eduardo David Enrique Naranjo Gutiérrez.png');
update public.miembros set foto = 'Alicia Cecilia Meza Pizarro.jpeg' where nombre = 'Alicia Cecilia Meza Pizarro' and (foto is distinct from 'Alicia Cecilia Meza Pizarro.jpeg');
update public.miembros set foto = 'Cristopher Bastian Jofré Campos.png' where nombre = 'Cristopher Bastian Jofré Campos' and (foto is distinct from 'Cristopher Bastian Jofré Campos.png');
update public.miembros set foto = 'Bárbara Elizabeth González Salazar.png' where nombre = 'Barbara Elizabeth Gonzalez Salazar' and (foto is distinct from 'Bárbara Elizabeth González Salazar.png');
update public.miembros set foto = 'Támara Elizabeth González León.png' where nombre = 'Támara Elizabeth Gonzalez Leon' and (foto is distinct from 'Támara Elizabeth González León.png');
update public.miembros set foto = 'Julio Anibal Ramírez Soto.png' where nombre = 'Julio Anibal Ramírez Soto' and (foto is distinct from 'Julio Anibal Ramírez Soto.png');
update public.miembros set foto = 'Walther Ivaniet Urbina Peña.png' where nombre = 'Walther Ivaniet Urbina Peña' and (foto is distinct from 'Walther Ivaniet Urbina Peña.png');
update public.miembros set foto = 'Héctor Ignacio León Pinto.png' where nombre = 'Hector Ignacio León Pinto' and (foto is distinct from 'Héctor Ignacio León Pinto.png');
update public.miembros set foto = 'David Francisco Flores Contreras.jpeg' where nombre = 'David Francisco Flores Contreras' and (foto is distinct from 'David Francisco Flores Contreras.jpeg');
update public.miembros set foto = 'Pascuala Blanca Arratia Zambrano.jpeg' where nombre = 'Pascuala Blanca Arratia Zambrano' and (foto is distinct from 'Pascuala Blanca Arratia Zambrano.jpeg');
update public.miembros set foto = 'Hernan Enrique Aravena Martínez.jpeg' where nombre = 'Hernan Enrique Aravena Martínez' and (foto is distinct from 'Hernan Enrique Aravena Martínez.jpeg');
update public.miembros set foto = 'Pilar de Lourdes Toro Pontigo.jpeg' where nombre = 'Pilar De Lourdes Toro Pontigo' and (foto is distinct from 'Pilar de Lourdes Toro Pontigo.jpeg');
update public.miembros set foto = 'Manuel Antonio Pailamilla Abarza.jpeg' where nombre = 'Manuel Antonio Pailamilla Abarza' and (foto is distinct from 'Manuel Antonio Pailamilla Abarza.jpeg');
update public.miembros set foto = 'Alicia del Carmen de Peña Jerez.png' where nombre = 'Alicia del Carmen de Peña Jerez' and (foto is distinct from 'Alicia del Carmen de Peña Jerez.png');
update public.miembros set foto = 'Andrea Francisca de Fuentes Molina.png' where nombre = 'Andrea Francisca de Fuentes Molina' and (foto is distinct from 'Andrea Francisca de Fuentes Molina.png');
update public.miembros set foto = 'Cristian Alexander Cortez Benavente.png' where nombre = 'Cristian Alexander Cortez Benavente' and (foto is distinct from 'Cristian Alexander Cortez Benavente.png');
update public.miembros set foto = 'Da Vía Rubio Lucas Maximiliano.jpeg' where nombre = 'Da Via Rubio Lucas Maximiliano' and (foto is distinct from 'Da Vía Rubio Lucas Maximiliano.jpeg');
update public.miembros set foto = 'Dafnhe Monserrat Echaniz Maripangui.png' where nombre = 'Dafnhe Monserrat Echaniz Maripangui' and (foto is distinct from 'Dafnhe Monserrat Echaniz Maripangui.png');
update public.miembros set foto = 'Daniela Beatriz Jeria Nuñez.png' where nombre = 'Daniela Beatriz Jeria Nuñez' and (foto is distinct from 'Daniela Beatriz Jeria Nuñez.png');
update public.miembros set foto = 'David Joel Ramos Torres.jpeg' where nombre = 'David Joel Ramos Torres' and (foto is distinct from 'David Joel Ramos Torres.jpeg');
update public.miembros set foto = 'Diego Aaron Miranda Acevedo.jpeg' where nombre = 'Diego Aaron Miranda Acevedo' and (foto is distinct from 'Diego Aaron Miranda Acevedo.jpeg');
update public.miembros set foto = 'Eduardo Alberto Castillo Fuentes.png' where nombre = 'Eduardo Alberto Castillo Fuentes' and (foto is distinct from 'Eduardo Alberto Castillo Fuentes.png');
update public.miembros set foto = 'Elias Benjamin Torres Jimenez.png' where nombre = 'Elias Benjamin Torres Jimenez' and (foto is distinct from 'Elias Benjamin Torres Jimenez.png');
update public.miembros set foto = 'Elvira del Carmen Núñez Ureta.jpeg' where nombre = 'Elvira del Carmen Nuñez Ureta' and (foto is distinct from 'Elvira del Carmen Núñez Ureta.jpeg');
update public.miembros set foto = 'Emma Maritza de Pineda Urra.jpeg' where nombre = 'Emma Maritza de Pineda Urra' and (foto is distinct from 'Emma Maritza de Pineda Urra.jpeg');
update public.miembros set foto = 'Eugenia Margarita de Wilches Martínez.jpeg' where nombre = 'Eugenia Margarita de Wilches Martinez' and (foto is distinct from 'Eugenia Margarita de Wilches Martínez.jpeg');
update public.miembros set foto = 'Fernanda Belén Meza Soto.png' where nombre = 'Fernanda Belen Meza Soto' and (foto is distinct from 'Fernanda Belén Meza Soto.png');
update public.miembros set foto = 'Fernando Andrés Soto Gazul.png' where nombre = 'Fernando Andres Soto Gazul' and (foto is distinct from 'Fernando Andrés Soto Gazul.png');
update public.miembros set foto = 'Francesco Alejandro Davía Rubio.jpeg' where nombre = 'Francesco Alejandro Da-via Rubio' and (foto is distinct from 'Francesco Alejandro Davía Rubio.jpeg');
update public.miembros set foto = 'Gonzalo Aaron Miranda Acevedo.jpeg' where nombre = 'Gonzalo Aaron Miranda Acevedo' and (foto is distinct from 'Gonzalo Aaron Miranda Acevedo.jpeg');
update public.miembros set foto = 'Ignacio Aaron Miranda Acevedo.jpeg' where nombre = 'Ignacio Aaron Miranda Acevedo' and (foto is distinct from 'Ignacio Aaron Miranda Acevedo.jpeg');
update public.miembros set foto = 'Iris del Pilar Duque Cáceres.jpeg' where nombre = 'Iris del Pilar Duque Caceres' and (foto is distinct from 'Iris del Pilar Duque Cáceres.jpeg');
update public.miembros set foto = 'Jesús Alberto Torres Benavente.png' where nombre = 'Jesus Alberto Torres Benavente' and (foto is distinct from 'Jesús Alberto Torres Benavente.png');
update public.miembros set foto = 'Joaquín Ignacio Torres Jiménez.png' where nombre = 'Joaquin Ignacio Torres Jimenez' and (foto is distinct from 'Joaquín Ignacio Torres Jiménez.png');
update public.miembros set foto = 'León Baltazar maureira peñailillo.png' where nombre = 'Leon Baltazar Maureira Peñailillo' and (foto is distinct from 'León Baltazar maureira peñailillo.png');
update public.miembros set foto = 'Leonardo Esteban Wilches Martínez.jpeg' where nombre = 'Leonardo Esteban Wilches Martinez' and (foto is distinct from 'Leonardo Esteban Wilches Martínez.jpeg');
update public.miembros set foto = 'Leonardo Nelson Wilches Santibáñez.png' where nombre = 'Leonardo Nelson Wilches Santibañez' and (foto is distinct from 'Leonardo Nelson Wilches Santibáñez.png');
update public.miembros set foto = 'Luciano Rafael Antonio Hernández Inostroza.jpeg' where nombre = 'Luciano Rafael Antonio Hernandez Inostroza' and (foto is distinct from 'Luciano Rafael Antonio Hernández Inostroza.jpeg');
update public.miembros set foto = 'Lucresia del Carmen de Delgado Atenas.jpeg' where nombre = 'Lucresia del Carmen de Delgado Atenas' and (foto is distinct from 'Lucresia del Carmen de Delgado Atenas.jpeg');
update public.miembros set foto = 'Luis Alberto Cornejo Mancilla.png' where nombre = 'Luis Alberto Cornejo Mancilla' and (foto is distinct from 'Luis Alberto Cornejo Mancilla.png');
update public.miembros set foto = 'Marco Antonio Hernandez Ruiz.png' where nombre = 'Marco Antonio Hernandez Ruiz' and (foto is distinct from 'Marco Antonio Hernandez Ruiz.png');
update public.miembros set foto = 'Margarita del Pilar de Meza Soto.jpeg' where nombre = 'Margarita del Pilar de Meza Soto' and (foto is distinct from 'Margarita del Pilar de Meza Soto.jpeg');
update public.miembros set foto = 'María Cristina Jiménez Ramírez.png' where nombre = 'Maria Cristina Jimenez Ramirez' and (foto is distinct from 'María Cristina Jiménez Ramírez.png');
update public.miembros set foto = 'Marisol Andrea de Hernandez Inostroza.jpeg' where nombre = 'Marisol Andrea de Hernandez Inostroza' and (foto is distinct from 'Marisol Andrea de Hernandez Inostroza.jpeg');
update public.miembros set foto = 'Mateo Alonso Hernández Inostroza.png' where nombre = 'Mateo Alonso Hernández Inostroza' and (foto is distinct from 'Mateo Alonso Hernández Inostroza.png');
update public.miembros set foto = 'Nahomi Maira Pañailillo Meza.png' where nombre = 'Nahomi Maira Pañailillo Meza' and (foto is distinct from 'Nahomi Maira Pañailillo Meza.png');
update public.miembros set foto = 'Nancy de Lourdes de Acevedo Rojas.jpeg' where nombre = 'Nancy de Lourdes de Acevedo Rojas' and (foto is distinct from 'Nancy de Lourdes de Acevedo Rojas.jpeg');
update public.miembros set foto = 'Nicolás Aarón Miranda Acevedo.jpeg' where nombre = 'Nicolás Aaron Miranda Acevedo' and (foto is distinct from 'Nicolás Aarón Miranda Acevedo.jpeg');
update public.miembros set foto = 'Paola Andrea de Castillo Silva.jpeg' where nombre = 'Paola Andrea de Castillo Silva' and (foto is distinct from 'Paola Andrea de Castillo Silva.jpeg');
update public.miembros set foto = 'Raúl Antonio Arce Huerta.png' where nombre = 'Raúl Antonio Arce Huerta' and (foto is distinct from 'Raúl Antonio Arce Huerta.png');
update public.miembros set foto = 'Romina Rubio Luna.jpeg' where nombre = 'Romina Rubio Luna' and (foto is distinct from 'Romina Rubio Luna.jpeg');
update public.miembros set foto = 'Santiago Solanille Clavero.png' where nombre = 'Santiago Solanille Clavero' and (foto is distinct from 'Santiago Solanille Clavero.png');
update public.miembros set foto = 'Verónica Elizabeth de Peñailillo Meza.png' where nombre = 'Veronica Elizabeth de Peñailillo Meza' and (foto is distinct from 'Verónica Elizabeth de Peñailillo Meza.png');
update public.miembros set foto = 'Víctor Manuel Román Jiménez.png' where nombre = 'Victor Manuel Roman Jimenez' and (foto is distinct from 'Víctor Manuel Román Jiménez.png');
update public.miembros set foto = 'Víctor Orlando Acevedo Nacaratte.png' where nombre = 'Victor Orlando Acevedo Nacaratte' and (foto is distinct from 'Víctor Orlando Acevedo Nacaratte.png');
commit;

-- Filas con foto: 70
