-- Fotos + organización por edad eclesiástica (2026)
-- Ejecutar en Supabase → SQL Editor → Run

begin;
update public.miembros set foto = 'Benjamín Alexander Vásquez Zolorsa.jpg', organizacion = 'Primaria' where nombre = 'Benjamín Alexander Vásquez Zolorsa';
update public.miembros set foto = 'Wladimir Antonio Sepúlveda Fuentes.jpg', organizacion = 'Cuórum de Presbíteros' where nombre = 'Wladimir Antonio Sepúlveda Fuentes';
update public.miembros set foto = 'Matias Ignacio Vega Abarca.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Matias Ignacio Vega Abarca';
update public.miembros set foto = 'Martina Francisca Escalante Cornejo.jpg', organizacion = 'Mensajeras de Esperanza' where nombre = 'Martina Francisca Escalante Cornejo';
update public.miembros set foto = 'Rosales Sánchez, Héctor Manuel.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Héctor Manuel Rosales Sanchez';
update public.miembros set foto = 'Mario Alejandro Rossel Poblete.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Mario Alejandro Rossel Poblete';
update public.miembros set foto = 'Graciela Del Carmen Arpe Torres.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Graciela Del Carmen Arpe Torres';
update public.miembros set foto = 'Isabella Esperanza Illanes Arpe.jpg', organizacion = 'Primaria' where nombre = 'Isabella Esperanza Illanes Arpe';
update public.miembros set foto = 'José Manuel Illanes Ceballos.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'José Manuel Illanes Ceballos';
update public.miembros set foto = 'Roberto Pablo Illanes Postigo.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Roberto Pablo Illanes Postigo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'María Laura Farias Fuentes';
update public.miembros set foto = 'Matías Alejandro Fuentes Martinez.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Matías Alejandro Fuentes Martinez';
update public.miembros set foto = 'Matías Valentín Leyes Campos.jpg', organizacion = 'Cuórum de Maestros' where nombre = 'Matias Valentin Leyes Campos';
update public.miembros set foto = 'Nahuel Nicolás Leyes Campos.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Nahuel Nicolás Leyes Campos';
update public.miembros set foto = 'Edgardo José Abarca Neira.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Edgardo Jose Abarca Neira';
update public.miembros set foto = 'Omar Ramon Ayala Roman.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Omar Ramon Ayala Roman';
update public.miembros set foto = 'Eduardo David Enrique Naranjo Gutiérrez.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Eduardo David Enrique Naranjo Gutierrez';
update public.miembros set foto = 'Alicia Cecilia Meza Pizarro.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Alicia Cecilia Meza Pizarro';
update public.miembros set foto = 'Cristopher Bastian Jofré Campos.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Cristopher Bastian Jofré Campos';
update public.miembros set foto = 'Bárbara Elizabeth González Salazar.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Barbara Elizabeth Gonzalez Salazar';
update public.miembros set organizacion = 'Cuórum de Maestros' where nombre = 'Mateo Ignacio León Silva';
update public.miembros set foto = 'Támara Elizabeth González León.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Támara Elizabeth Gonzalez Leon';
update public.miembros set foto = 'Julio Anibal Ramírez Soto.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Julio Anibal Ramírez Soto';
update public.miembros set foto = 'Walther Ivaniet Urbina Peña.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Walther Ivaniet Urbina Peña';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Fernando Alonso Cerda Poblete';
update public.miembros set foto = 'Héctor Ignacio León Pinto.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Hector Ignacio León Pinto';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Yoel Alejandro Córdova González';
update public.miembros set organizacion = 'Primaria' where nombre = 'Tomas Alejandro Cortez Daza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Gabriela Soledad Contreras Zuñiga';
update public.miembros set organizacion = 'Guardianas de Luz' where nombre = 'Josefa Paz Diaz Jeria';
update public.miembros set organizacion = 'Cuórum de Diáconos' where nombre = 'Felipe Esteban Pinto Jauregui';
update public.miembros set foto = 'José Miguel Diaz Muñoz.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'José Miguel Diaz Muñoz';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Thiare Andrea Donoso Vilches';
update public.miembros set organizacion = 'Primaria' where nombre = 'Dominique Dayanet Donoso Vilches';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Claudia Maricel Vilches Arenas';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Pedro Leon Walker Ramirez';
update public.miembros set foto = 'David Francisco Flores Contreras.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'David Francisco Flores Contreras';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Nancy Del Carmen Varas Nitor';
update public.miembros set foto = 'Pascuala Blanca Arratia Zambrano.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Pascuala Blanca Arratia Zambrano';
update public.miembros set organizacion = 'Guardianas de Luz' where nombre = 'Javiera Antonia Núñez Pineda';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Rosa del Carmen Pardo Basaure';
update public.miembros set foto = 'Hernan Enrique Aravena Martínez.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Hernan Enrique Aravena Martínez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Catalina Ignacia Aravena Toro';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Carlos Fernando Soto Godoy';
update public.miembros set foto = 'Pilar de Lourdes Toro Pontigo.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Pilar De Lourdes Toro Pontigo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Alejandro Luis Castro Silva';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Camilo Andrés Farias Ortega';
update public.miembros set foto = 'Manuel Antonio Pailamilla Abarza.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Manuel Antonio Pailamilla Abarza';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Eduardo Acevedo Mendoza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Silvia Del Carmen Delgado Abarzua';
update public.miembros set organizacion = 'Guardianas de Luz' where nombre = 'Isidora Ignacia Riquelme Jofre';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Nicolas Gabriel Hauser Rogget';
update public.miembros set organizacion = 'Primaria' where nombre = 'Felipe Octavio Caceres Olivera';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Andres Felipe Erazo Salgado';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Abel del Transito Meza Toro';
update public.miembros set organizacion = 'Cuórum de Diáconos' where nombre = 'Agustin Facundo Flores Martinez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Agustin Javier Ignacio Berrios Berrios';
update public.miembros set organizacion = 'Guardianas de Luz' where nombre = 'Ahiza Lía Pizarro Hernández';
update public.miembros set foto = 'Alejandro Alberto Sanchez Celis.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Alejandro Alberto Sanchez Celis';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Alejandro Ignacio Bugueño Hormazábal';
update public.miembros set foto = 'Alfredo Elias Mondaca Riveros.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Alfredo Elias Mondaca Riveros';
update public.miembros set foto = 'Alicia del Carmen de Peña Jerez.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Alicia del Carmen de Peña Jerez';
update public.miembros set foto = 'Alina Yolanda Gazul Ortega.jpeg', organizacion = 'Sociedad de Socorro' where nombre = 'Alina Yolanda de Soto Gazul';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Alvaro Alejandro Claudio Da Viá Campbell';
update public.miembros set organizacion = 'Mensajeras de Esperanza' where nombre = 'Amanda Carolina Castillo Silva';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Ana Maria Vicencio Munita';
update public.miembros set organizacion = 'Edificadoras de Fe' where nombre = 'Andrea Eloísa Castillo Silva';
update public.miembros set foto = 'Andrea Francisca de Fuentes Molina.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Andrea Francisca de Fuentes Molina';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Andrea Jaqueline Jofre Aravena';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Andres Rolando Gonzalez Salazar';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Angelica de las Nieves Naranjo Gallardo';
update public.miembros set organizacion = 'Mensajeras de Esperanza' where nombre = 'Antonia Pascal Torres Silva';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Barbara de las Mercedes Santis Figueroa';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Bernarda Cristina Hernandez Fuentes';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Bernarda de Lourdes Cardenas Zenteno';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Byron Broderyk Oroz Ravanal';
update public.miembros set foto = 'Camila Fernanda Farias Alvarez.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Camila Fernanda Farias Alvarez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Carla Belen Fajardo Lara';
update public.miembros set organizacion = 'Mensajeras de Esperanza' where nombre = 'Carla Belén Oroz Ravanal';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Carlos Francisco Martinez Martinez';
update public.miembros set organizacion = 'Primaria' where nombre = 'Carlos Horacio Flores Martínez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Carlos Ivan Cárdenas Sanchez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Carlos Samuel Contreras Gaona';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Carmen Gloria Tapia Melendez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Carolina Andrea Fuentes Inayao';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Caroline Pallan Rojas Koneffke';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Catalina Belen Gana Luna';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Catherine Estrella de Carrasco Felix';
update public.miembros set foto = 'Cesar Aaron Miranda Cabello.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Cesar Aaron Miranda Cabello';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Cesar Alejandro Contreras Toro';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'César Antonio Chavez Figueroa';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Clemira Ester Gonzalez Gonzalez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Constanza Alexandra Arce Vidal';
update public.miembros set organizacion = 'Guardianas de Luz' where nombre = 'Constanza Antonia Astorga Hernandez';
update public.miembros set foto = 'Cristian Alexander Cortez Benavente.jpg', organizacion = 'Cuórum de Diáconos' where nombre = 'Cristian Alexander Cortez Benavente';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Cristian Ignacio Ampuero Ampuero';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Cristian Pablo Ortega Silva';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Cristina del Carmen de Meza Soto';
update public.miembros set foto = 'Da Vía Rubio Lucas Maximiliano.jpg', organizacion = 'Primaria' where nombre = 'Da Via Rubio Lucas Maximiliano';
update public.miembros set foto = 'Dafnhe Monserrat Echaniz Maripangui.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Dafnhe Monserrat Echaniz Maripangui';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Daniel Andres Delgado Atenas';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Daniel Ignacio Wilches Martinez';
update public.miembros set foto = 'Daniela Beatriz Jeria Nuñez.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Daniela Beatriz Jeria Nuñez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Daniela Francisca Vera Trincado';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'David Alejandro Quintanilla Meza';
update public.miembros set foto = 'David Joel Ramos Torres.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'David Joel Ramos Torres';
update public.miembros set foto = 'Diego Aaron Miranda Acevedo.jpg', organizacion = 'Cuórum de Diáconos' where nombre = 'Diego Aaron Miranda Acevedo';
update public.miembros set foto = 'Diego Cristobal Delgado Atenas.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Diego Cristobal Delgado Atenas';
update public.miembros set foto = 'Eduardo Alberto Castillo Fuentes.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Eduardo Alberto Castillo Fuentes';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Eliana de las Mercedes Figueroa Berrios';
update public.miembros set foto = 'Elias Benjamin Torres Jimenez.jpg', organizacion = 'Primaria' where nombre = 'Elias Benjamin Torres Jimenez';
update public.miembros set organizacion = 'Primaria' where nombre = 'Eliette Belen Martez Hernadez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Elizabeth Macarena Jeria Zuñiga';
update public.miembros set foto = 'Elvira del Carmen Núñez Ureta.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Elvira del Carmen Nuñez Ureta';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Ema Beatriz Soto Zuñiga';
update public.miembros set organizacion = 'Guardianas de Luz' where nombre = 'Emilia Monzerat Hernandez Jara';
update public.miembros set foto = 'Emma Maritza de Pineda Urra.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Emma Maritza de Pineda Urra';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Ernesto Ulises Rodriguez Medel';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Esteban Advis Jara';
update public.miembros set foto = 'Eugenia Margarita de Wilches Martínez.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Eugenia Margarita de Wilches Martinez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Evelyn Romina Silva Aguilar';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Evelyn Susana Riquelme Cuevas';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Felipe Ignacio Riquelme Cornejo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Felipe Osvaldo Cortez Vera';
update public.miembros set organizacion = 'Cuórum de Maestros' where nombre = 'Félix Francisco Julian Pizarro Hernández';
update public.miembros set foto = 'Fernanda Belén Meza Soto.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Fernanda Belen Meza Soto';
update public.miembros set foto = 'Fernando Andrés Soto Gazul.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Fernando Andres Soto Gazul';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Fernando Antonio Cerda Paredes';
update public.miembros set organizacion = 'Primaria' where nombre = 'Flores Martinez Consuelo Rosario';
update public.miembros set foto = 'Francesco Alejandro Davía Rubio.jpg', organizacion = 'Primaria' where nombre = 'Francesco Alejandro Da-via Rubio';
update public.miembros set organizacion = 'Edificadoras de Fe' where nombre = 'Francisca Fernanda Oroz Ravanal';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Fredy Felipe Silva Osorio';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Gabriela Evelyn Vargas Soto';
update public.miembros set organizacion = 'Cuórum de Presbíteros' where nombre = 'Gaspar Emilio Cofre Hernández';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Gerardo Andres Aburto Velasquez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Gerardo Andres Quijada Gonzalez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Gladys de las Mercedes Vera Diaz';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Gladys del Carmen Zuñiga Castillo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Gloria Virginia de Naranjo Gallardo';
update public.miembros set foto = 'Gonzalo Aaron Miranda Acevedo.jpg', organizacion = 'Primaria' where nombre = 'Gonzalo Aaron Miranda Acevedo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Graciela Rosa Cáceres Monarde';
update public.miembros set foto = 'Gustavo Adolfo Gana Luna.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Gustavo Adolfo Gana Luna';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Hector Rigoberto Rocha Corral';
update public.miembros set organizacion = 'Cuórum de Maestros' where nombre = 'Ian Aaron Cobarrubia Maripangui';
update public.miembros set foto = 'Ignacio Aaron Miranda Acevedo.jpg', organizacion = 'Cuórum de Presbíteros' where nombre = 'Ignacio Aaron Miranda Acevedo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Ignacio Alberto Vega Badilla';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Ignacio Juan Caceres Olivera';
update public.miembros set foto = 'Iris del Pilar Duque Cáceres.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Iris del Pilar Duque Caceres';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Irma de las Mercedes Jara Rojas';
update public.miembros set organizacion = 'Primaria' where nombre = 'Isabella Aurora Bustos Farias';
update public.miembros set organizacion = 'Primaria' where nombre = 'Isabella Selenne Acevedo Labrin';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Ivan Lev-Aaron Carrasco Felix';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Ivan Marcelo Carrasco Carrasco';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Javiera Beatriz Vidal Basso';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Jennifer Odette Ravanal Echeverria';
update public.miembros set foto = 'Jesús Alberto Torres Benavente.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Jesus Alberto Torres Benavente';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jesus Antonio Quijada Gonzalez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jhon Alexander Sandoval Basulto';
update public.miembros set foto = 'Joaquín Ignacio Torres Jiménez.jpg', organizacion = 'Cuórum de Diáconos' where nombre = 'Joaquin Ignacio Torres Jimenez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jorge Armando Guerrero Ortega';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jorge Jose Vera Delgado';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jose Fernando Antonio Santacana Salinas';
update public.miembros set organizacion = 'Primaria' where nombre = 'José Ignacio Cartagena Meza';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jose Javier Castro Torres';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Jose Miguel Soto Gazul';
update public.miembros set foto = 'Jose Miguel Soto Soto.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Jose Miguel Soto Soto';
update public.miembros set foto = 'Juan Antonio Meza Meza.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Juan Antonio Meza Meza';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Carlos Armijo Acevedo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Carlos Caceres Martinez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Carlos Hernandez Donoso';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Carlos Oroz Caceres';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Carlos Taborga Navia';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Carlos Zuñiga Lisboa';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Francisco Bravo Golling';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Francisco Vera Pavez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Manuel Martinez Castillo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Juan Pablo Enrique Avendaño Avendaño';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Juanita Ester Ugarte Herrera';
update public.miembros set organizacion = 'Primaria' where nombre = 'Julieta Ignacia Soto Velásquez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Julio Alberto Farias Menares';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Karen Andrea Diaz Fuenzalida';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Karen Liliana Márquez Grande';
update public.miembros set foto = 'Katherine Yamilet Marquez Grande.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Katherine Yamilet Marquez Grande';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Kevin Alan Robinson Tilleria';
update public.miembros set organizacion = 'Mensajeras de Esperanza' where nombre = 'Laura Agustina de Jesus Parraguez Meza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Laura Elizabeth de Miranda Acevedo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Laura Lavinia de Rubio Luna';
update public.miembros set foto = 'León Baltazar maureira peñailillo.jpg', organizacion = 'Primaria' where nombre = 'Leon Baltazar Maureira Peñailillo';
update public.miembros set foto = 'Leonardo Esteban Wilches Martínez.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Leonardo Esteban Wilches Martinez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Leonardo Gerardo Vera Atenas';
update public.miembros set foto = 'Leonardo Nelson Wilches Santibáñez.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Leonardo Nelson Wilches Santibañez';
update public.miembros set foto = 'Luciano Rafael Antonio Hernández Inostroza.jpg', organizacion = 'Primaria' where nombre = 'Luciano Rafael Antonio Hernandez Inostroza';
update public.miembros set foto = 'Lucresia del Carmen de Delgado Atenas.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Lucresia del Carmen de Delgado Atenas';
update public.miembros set foto = 'Luis Alberto Cornejo Mancilla.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Luis Alberto Cornejo Mancilla';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Luis Mariano Hinojosa Cerda';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Luis Martin Lassaube Lassaube';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Luisa del Carmen Peso Huenchuan';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Luz Angelica de Pardo Millares';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Luz Eliana Paillamil Meza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Luz Maria de Berrios Peña';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Manuel Antonio Vasquez Jerez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Manuel Armando Perez Ormazabal';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Manuel Ignacio Ampuero Soto';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Manuel Jesus Ampuero Montes';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Marcela Antonia Pardo Martinez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Marcela Ivon Donaire Valladares';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Marcelina del Carmen de Soto Soto';
update public.miembros set foto = 'Marco Antonio Hernandez Ruiz.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Marco Antonio Hernandez Ruiz';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Marco Antonio Marco Antonio Hernandez Trujillo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Margarita Alejandra Pardo Perez';
update public.miembros set foto = 'Margarita del Pilar de Meza Soto.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Margarita del Pilar de Meza Soto';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Margarita Elena de Soto Abarca';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Margarita Elizabeth de Bugueño Hormazabal';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'María Alejandra Gaona Quintanilla';
update public.miembros set foto = 'Maria Cristina Jimenez Ramirez.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Maria Cristina Jimenez Ramirez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Maria del Carmen Alfaro de Flores';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Maria Enriqueta Vidal Diaz';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Maria Fernanda Duran Verdugo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Maria Jose Velasquez Contreras';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Marielín Alejandra Bracho de Jimenez';
update public.miembros set foto = 'Marina Enriqueta Martinez Castillo.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Marina Enriqueta Martinez Castillo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Mario Ismael Silva Chavez';
update public.miembros set foto = 'Marisol Andrea de Hernandez Inostroza.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Marisol Andrea de Hernandez Inostroza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Marisol del Carmen de Vasquez Soto';
update public.miembros set foto = 'Maritza Viviana Martinez de Flores.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Maritza Viviana Martinez de Flores';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Marjorie Andrea Hernández Arellano';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Marlon Jose Jimenez Dominguez';
update public.miembros set foto = 'Marta Irene Celis Gongora.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Marta Irene Celis Gongora';
update public.miembros set organizacion = 'Cuórum de Diáconos' where nombre = 'Mateo Alonso Bustos Farias';
update public.miembros set foto = 'Mateo Alonso Hernández Inostroza.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Mateo Alonso Hernández Inostroza';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Matías Reinaldo Montecinos Montecinos';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Matilde Josefina Chourio de Bracho';
update public.miembros set foto = 'Mauricio Fernando Flores Rojas.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Mauricio Fernando Flores Rojas';
update public.miembros set organizacion = 'Cuórum de Diáconos' where nombre = 'Maximiliano Antonio Berridos Arancibia';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Mayte Belen Carrasco Felix';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Melanie Soledad Coral Om Gutierrez Peso';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Melissa Andrea Maripangui Vidal';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Michel Andreina Colmenarez Chirinos';
update public.miembros set organizacion = 'Edificadoras de Fe' where nombre = 'Milena Paz Andrea Om Hernandez Inostroza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Monica Alejandra de Orozco Frias';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Monica Elena Luna Belmar';
update public.miembros set foto = 'Nahomi Maira Pañailillo Meza.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Nahomi Maira Pañailillo Meza';
update public.miembros set foto = 'Nancy de Lourdes de Acevedo Rojas.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Nancy de Lourdes de Acevedo Rojas';
update public.miembros set foto = 'Nicolás Aarón Miranda Acevedo.jpg', organizacion = 'Primaria' where nombre = 'Nicolás Aaron Miranda Acevedo';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Nicolas Rodrigo Fajardo Lara';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Nicolas Rodrigo Soto Soto';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Nicole Emilia Contreras Berrios';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Nora Angelica Martinez Riquelme';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Nora del Carmen Riquelme Inostroza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Olga Luisa Pardo Millares';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Oscar Ignacio Soto Soto';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Oscar Ricardo Faris Bustos';
update public.miembros set foto = 'Paola Andrea de Castillo Silva.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Paola Andrea de Castillo Silva';
update public.miembros set organizacion = 'Edificadoras de Fe' where nombre = 'Pascal Noemi Tobar Arancibia';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Patricia Elsa Maria de Cornejo Zablach';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Patricio Alejandro Delgado Atenas';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Paula Andrea Pardo Perez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Paulina de los Angeles Berrios Meza';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Pedro Mauricio Hernández González';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Pilar Catherine Castillo Silva';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Rachel Jasmin Vidal Martinez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Rafael Leopoldo Mercedes de Vera Flores';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Raul Alfredo Vidal Martinez';
update public.miembros set foto = 'Raúl Antonio Arce Huerta.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Raúl Antonio Arce Huerta';
update public.miembros set foto = 'Rene Alberto Gana Gatica.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Rene Alberto Gana Gatica';
update public.miembros set foto = 'Rene Axel Gana Luna.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Rene Axel Gana Luna';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Rita Esperanza Estrella Om Marsa Miranda';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Rocio Rubio Luna';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Rodrigo Andres Martinez Manosalva';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Rodrigo Sebastian Vidal Martinez';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Romina Ester Soto Soto';
update public.miembros set foto = 'Romina Rubio Luna.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Romina Rubio Luna';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Rosa Natividad Herrera Ancain';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Rossana del Pilar de Robinson Tilleria';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Roxanna Soledad Meza Morales';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Sandra Jazmine de Vera Campos';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Sandy Marion Ramirez Roa';
update public.miembros set foto = 'Santiago Solanille Clavero.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Santiago Solanille Clavero';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Sarah Nazaret Lassaube Lopez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Sebastian Andres de Jesus Hinojosa Cerda';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Sebastian Antonio Mori Lassaube';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Sebastian Ignacio Miranda Cabello';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Segundo Andres Naranjo Alvarez';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Sergio Enrique Pineda Soto';
update public.miembros set foto = 'Silvana del Carmen de Gana Luna.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Silvana del Carmen de Gana Luna';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Silvia Georgina Olivera Delgado';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Smith las Mercedes Saint Julien';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Sofia de los Angeles Bustos Opitz';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Teresa Sandra Cabello Torres';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Teresita del Carmen de Fajardo Lara';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Thiago Cárdenas Zenteno';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Treacy Scarlett Oroz Ravanal';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Ulises Gonzalo Cerda Paredes';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Valeska del Carmen Miranda Loyola';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Vanessa Esmeralda Vera Atenas';
update public.miembros set organizacion = 'Edificadoras de Fe' where nombre = 'Vasquez Soto Renata Antonio';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Veronica del Carmen Guardera Maldonado';
update public.miembros set foto = 'Verónica Elizabeth de Peñailillo Meza.jpg', organizacion = 'Sociedad de Socorro' where nombre = 'Veronica Elizabeth de Peñailillo Meza';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Veronica Paola Vera Campos';
update public.miembros set organizacion = 'Cuórum de Élderes' where nombre = 'Victor Alejandro Acevedo Rojas';
update public.miembros set foto = 'Víctor Manuel Román Jiménez.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Victor Manuel Roman Jimenez';
update public.miembros set foto = 'Víctor Orlando Acevedo Nacaratte.jpg', organizacion = 'Cuórum de Élderes' where nombre = 'Victor Orlando Acevedo Nacaratte';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Viviana Jacqueline Martinez Castillo';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Wilhermina Francisca de Molina Zuñiga';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Yasna Karen Hernandez Rojas';
update public.miembros set organizacion = 'Cuórum de Diáconos' where nombre = 'Yeiko Leon Cobarrubia Maripangui';
update public.miembros set organizacion = 'Sociedad de Socorro' where nombre = 'Yhanela Danaee Echaniz Maripangui';
commit;

-- Año eclesiástico: 2026
-- Fotos actualizadas: 40, orgs: 0
