/* Índice de fotos de perfil — usado por admin (asistencia) */
window.FOTOS_INDEX = {
  overrides: {
    "alina de gazul soto yolanda": "Alina Yolanda Gazul Ortega.jpeg",
  },
  files: [
    "643322059_10240714748943640_1804666815657664619_n.jpg",
    "Alfredo Elias Mondaca Riveros.jpg",
    "Alicia Cecilia Meza Pizarro.jpg",
    "Alicia del Carmen de Peña Jerez.jpg",
    "Alina Yolanda Gazul Ortega.jpeg",
    "Andrea Francisca de Fuentes Molina.png",
    "Bárbara Elizabeth González Salazar.png",
    "Benjamín Alexander Vásquez Zolorsa.png",
    "Cesar Aaron Miranda Cabello.jpg",
    "Cristian Alexander Cortez Benavente.png",
    "Cristopher Bastian Jofré Campos.jpg",
    "Da Vía Rubio Lucas Maximiliano.jpeg",
    "Dafnhe Monserrat Echaniz Maripangui.png",
    "Daniela Beatriz Jeria Nuñez.jpg",
    "David Francisco Flores Contreras.jpeg",
    "David Joel Ramos Torres.jpg",
    "Diego Aaron Miranda Acevedo.jpg",
    "Edgardo José Abarca Neira.png",
    "Eduardo Alberto Castillo Fuentes.png",
    "Eduardo David Enrique Naranjo Gutiérrez.png",
    "Elias Benjamin Torres Jimenez.jpg",
    "Elvira del Carmen Núñez Ureta.jpg",
    "Emma Maritza de Pineda Urra.jpg",
    "Eugenia Margarita de Wilches Martínez.jpeg",
    "Fernanda Belén Meza Soto.jpg",
    "Fernando Andrés Soto Gazul.png",
    "Francesco Alejandro Davía Rubio.jpeg",
    "Gonzalo Aaron Miranda Acevedo.jpg",
    "Graciela Del Carmen Arpe Torres.jpg",
    "Gustavo Adolfo Gana Luna.png",
    "Héctor Ignacio León Pinto.png",
    "Hernan Enrique Aravena Martínez.jpg",
    "Ignacio Aaron Miranda Acevedo.jpeg",
    "Iris del Pilar Duque Cáceres.jpeg",
    "Isabella Esperanza Illanes Arpe.png",
    "Jesús Alberto Torres Benavente.png",
    "Joaquín Ignacio Torres Jiménez.png",
    "José Manuel Illanes Ceballos.png",
    "Jose Miguel Soto Soto.jpeg",
    "Julio Anibal Ramírez Soto.png",
    "Katherine Yamilet Marquez Grande.jpg",
    "Laura Elizabeth Acevedo Rojas.png",
    "León Baltazar maureira peñailillo.png",
    "Leonardo Esteban Wilches Martínez.jpg",
    "Leonardo Nelson Wilches Santibáñez.jpg",
    "Luciano Rafael Antonio Hernández Inostroza.jpg",
    "Lucresia del Carmen de Delgado Atenas.jpg",
    "Luis Alberto Cornejo Mancilla.jpg",
    "Manuel Antonio Pailamilla Abarza.jpg",
    "Marco Antonio Hernandez Ruiz.png",
    "Margarita del Pilar de Meza Soto.jpg",
    "Maria Cristina Jimenez Ramirez.jpg",
    "Marina Enriqueta Martinez Castillo.png",
    "Mario Alejandro Rossel Poblete.png",
    "Marisol Andrea de Hernandez Inostroza.jpg",
    "Maritza Viviana Martinez de Flores.jpg",
    "Martina Francisca Escalante Cornejo.png",
    "Mateo Alonso Hernández Inostroza.png",
    "Matías Alejandro Fuentes Martinez.png",
    "Matias Ignacio Vega Abarca.png",
    "Matías Valentín Leyes Campos.png",
    "Mauricio Fernando Flores Rojas.jpg",
    "Nahomi Maira Pañailillo Meza.jpg",
    "Nahuel Nicolás Leyes Campos.png",
    "Nancy de Lourdes de Acevedo Rojas.png",
    "Nicolás Aarón Miranda Acevedo.jpg",
    "Omar Ramon Ayala Roman.png",
    "Paola Andrea de Castillo Silva.jpg",
    "Pascuala Blanca Arratia Zambrano.jpg",
    "Pilar de Lourdes Toro Pontigo.jpg",
    "Raúl Antonio Arce Huerta.png",
    "Rene Alberto Gana Gatica.jpg",
    "Rene Axel Gana Luna.jpg",
    "Roberto Pablo Illanes Postigo.png",
    "Romina Rubio Luna.jpeg",
    "Rosales Sánchez, Héctor Manuel.png",
    "Santiago Solanille Clavero.jpg",
    "Silvana del Carmen de Gana Luna.jpg",
    "Támara Elizabeth González León.png",
    "Verónica Elizabeth de Peñailillo Meza.png",
    "Víctor Manuel Román Jiménez.png",
    "Víctor Orlando Acevedo Nacaratte.jpg",
    "Walther Ivaniet Urbina Peña.png",
    "Wladimir Antonio Sepúlveda Fuentes.png",
  ],
};
